# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DisasterMappingPrioritization
                                 A QGIS plugin
 This plugin adds an algorithm to save attributes of selected layer as a CSV file
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-14
        copyright            : (C) 2023 by Open Mapping Hub Asia-Pacific
        email                : honey.fombuena@hotosm.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Open Mapping Hub Asia-Pacific'
__date__ = '2023-02-14'
__copyright__ = '(C) 2023 by Open Mapping Hub Asia-Pacific'



# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DisasterMappingPrioritizationclass from file DisasterMappingPrioritization.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .disaster_mapping_prioritization import DisasterMappingPrioritizationPlugin
    return DisasterMappingPrioritizationPlugin(iface)